### PR TITLE
Maintenance

### PR DESCRIPTION
**Pull request by cbm755**
Trying to Fix Issue #72...  Following the nice directions at https://johannesjh.github.io/req2flatpak/main/development.html#ensuring-code-quality

So far:
- [x] `pre-commit run --all`
- [x] `poetry update`

### CODE REVIEW

**Comment by cbm755** [comment]
In the docs, I don't know what [this instruction means](https://johannesjh.github.io/req2flatpak/main/development.html#pre-commit-hooks)?

```
# 4. Remove `frozen: x.x.x` comments for unfrozen dependencies
```

How am I supposed to know which are frozen?  

Note that step 1 `pre-commit autoupdate --freeze` has some of its changes undone by step 3 `pre-commit run`.   Might be nice to clarify this part a bit more in the manual...

**Comment by johannesjh** [comment]
I have to say I am having a hard time myself following these instructions (despite the fact that I personally wrote them, if I remember well). I guess we need to improve and correct the instructions. Specifically, I think we can remove step 4 from the instructions.

**Comment by johannesjh** [comment]
I guess we should merge the two sections for updating poetry vs. pre-commit dependencies because they are rather intermingled. If I understand the workings of `sync_with_poetry` correctly, we should proceed as follows

first update poetry dependecies:

1. manually bump the version constraints in `pyproject.toml`
2. run `poetry update` to update packages and write the lock file
3. run `poetry install --with lint --all-extras` to update the local python environment
4. run `git add pyproject.toml poetry.lock` to stage the changes in git

then update pre-commit dependencies:

1. run `pre-commit install` just to be sure that pre-commit is properly initialized
2. run `pre-commit autoupdate --freeze` to update pre-commit's packages
3. run `git add .pre-commit-config.yaml` to stage changes
4. run `pre-commit run` to sync package versions from poetry to pre-commit. note, this is a one-way-sync, i.e., the package versions defined in the poetry lock file are copied over to the pre-commit yaml file.
5. stage changes using git
6. run `pre-commit run` to verify that pre-commit now happily leaves all files unchanged
7. stage and commit all changes.

**Comment by cbm755** [comment]
thanks very much, that is much clearer!

This should be ready to merge and fixes #74.

**Review by johannesjh — APPROVED** [review]

**Pull request merged**
