### PR TITLE
Poetry hook

### PR DESCRIPTION
**Pull request by real-yfprojects**
* cleanup ordering in pyproject.toml
* add pre-commit hooks for `poetry check` and `poetry lock`

### CODE REVIEW

**Comment by real-yfprojects** [comment]
Poetry lock slows down the pre-commit hooks considerably.

**Comment by johannesjh** [comment]
Note, the failed linting is probably due to https://github.com/klen/pylama/issues/232

**Review by johannesjh — APPROVED** [review]

**Comment by real-yfprojects** [comment]
> Note, the failed linting is probably due to [klen/pylama#232](https://github.com/klen/pylama/issues/232)

Can we lock the pydocstyle version in poetry?

**Comment by johannesjh** [comment]
Yes, locking the version of pydocstyle to 6.1.x should be effective, judging from the root cause analysis in https://github.com/PyCQA/pydocstyle/issues/621. I tried locking its version but for some reason this did not help, not sure why... maybe pre-commit did not use poetry to resolve the version of pydocstyle.

**Comment by real-yfprojects** [comment]
> I tried locking its version but for some reason this did not help, not sure why... maybe pre-commit did not use poetry to resolve the version of pydocstyle.

Works for me when using `poetry add 'pydocstyle<6.2'`. How did you do it?

**Pull request merged**
