### PR TITLE
Expand `pyproject.toml` and adjust `ci.yml`.

### PR DESCRIPTION
**Pull request by real-yfprojects**
* pyproject.toml (tool.poetry): Add group `docs` and move matching deps to it.
	Rename group `dev` to `lint`. For testing deps another group named `tests` or
	`testing` could be added.

* pyproject.toml : Add configuration for `isort`, `pydocstyle` and `pylint`.

* .pylintrc : Remove because its config is now included in `pyproject.toml`.

* .pre-commit-config.yaml : Remove cmd options that are configured in `pyproject.toml`.

* .github/actions/setup/action.yml : Add input for passing additional args to `poetry install`.

* .github/workflows/ci.yml : Specify groups to install for each job. Their setup will be faster
	now because they don't install unnecessary deps.

* .github/workflows/ci.yml (jobs.lint): Lint a second time after installing extras (optional deps)

### CODE REVIEW

**Comment by real-yfprojects** [comment]
Do you want to ignore `C0301` (lines too long) or fix the lines that are too long?

**Comment by johannesjh** [comment]
I'd rather ignore long lines.

Rationale: the black formatter does a pretty good job at keeping line lengths short in most situations... with some exceptions where lines are difficult to shorten, e.g., lines containing a long string. In these situation's, I think it is acceptable (and sometimes very practical and reasonable) to live with longer lines.

**Comment by johannesjh** [comment]
very nice refactoring, thank you! (feel free to merge once the linting checks are green)

**Comment by real-yfprojects** [comment]
I would like to use `mypy`, `pylama` and `bandit` for development. Should I include them in `pyproject.toml` and install them with poetry? It seems like poetry doesn't support local dev dependencies.

**Comment by johannesjh** [comment]
yes, you can include these tools in pyproject.toml. (judging from its readme, pylama already includes mypy as an optional dependency).

Some thoughts: pylama is new to me, it sounds like a useful combination of tools. 
* pylama supports pycodestyle aka pep8, not sure about black. please make sure it plays nicely with black... I value the convenience of auto-formatted code more than the nagging criticim of linters :-)
* pylama integrates mypy, which would be a good fit for req2flatpak's code because we already use typing a lot.
* pylama does not integrate bandit, so this would have to be configured separately... should be no problem.

**Comment by real-yfprojects** [comment]
Will look into that. Currently I have these tools integrated into my IDE for all kinds of python projects.

**Comment by real-yfprojects** [comment]
> pylama supports pycodestyle aka pep8, not sure about black. please make sure it plays nicely with black... I value the convenience of auto-formatted code more than the nagging criticim of linters

Its possible to disable specific tools that pylama wraps. Pycodestyle can be used with black since it is what flake8 wraps and the black docs explain how to use flake8 along black. My question is: Which pylama linters do we want?

**Comment by johannesjh** [comment]
> Which pylama linters do we want?

I'd suggest:

* pycodestyle: yes, together with black. (thx for researching about their mutual compatibility)
* pydocstyle: yes, we are using it already, it is picky, but it is mostly right when it complains about something.
* pyflakes: yes, a strong yes
* pylint: yes. I mean, it complains a lot, but it does provide valuable feedback. and it is usually quick to either fix the issue, or to make an exception.
* mcCabe and radon: rather no. my past subjective experience is that it did not provide valuable feedback. e.g., it complained about long procedural code where one step follows another... stating that the code was too complex, to many if-decisions and too many variables. but splitting up the code into multiple methods just to improve the score does not always make the code easier to understand.
* mypy: yes. I started using it, and it did provide valuable feedback. It did find outright bugs, very useful. And it did find minor issues that were easy to fix by e.g., adding type hints.
* eradicate: yes. I have not used it before but I don't expect any troubles, so why not.
* vulture: not sure. the python api provides methods that are (hopefully) useful even though the CLI does not call them. I am therefore skeptical if an automated tool like vulture can provide valuable feedback in the case of req2flatpak.

...plus bandit, I have not worked with it, but I have heard good things.

**Comment by real-yfprojects** [comment]
I don't like that one has to place the configuration into blocks like `tool.pylama.linter.pydocstyle` since that doesn't apply running `pydocstyle` on its own. The same applies for `pycodestyle` which also needs `setup.cfg` since it doesn't support `pyproject.toml` on its own.

> the python api provides methods that are (hopefully) useful even though the CLI does not call them.

You are talking about `req2flatpak`?

> I am therefore skeptical if an automated tool like vulture can provide valuable feedback in the case of req2flatpak.

I think, `vulture` is a useful tool that can provide valuable feedback for development on `req2flatpak`. However not when used as an automated tool in a pre-commit-hook. In our case there will be a lot of false positives and considering that this is only a small project, it probably doesn't make sense to use the tool frequently.

Another question: Would you like to run mypy on the tests also? I don't think type safety is needed there. The test code may be dirty.

**Comment by johannesjh** [comment]
>> the python api provides methods that are (hopefully) useful even though the CLI does not call them.

> You are talking about req2flatpak?

yes, sorry, that was not clear. I was talking about req2flatpak's python api (i.e., its python classes), that people can use when writing their own script. not all of req2flatpak's api functionality is exposed in the CLI; this would probably be seen as dead code.

about vulture: I agree.

about running mypy on the tests: rather yes. I would not mind running mypy against the test code. I don't think it will take a lot of effort to make the test code clean with correct typing, and I think it will help in the long run.

**Pull request merged**
