### PR TITLE
Replace pkg_resources with packaging

### LINKED ISSUE #64: Use of pkg_resources is deprecated
https://setuptools.pypa.io/en/latest/pkg_resources.html

### PR DESCRIPTION
**Pull request by real-yfprojects**
This pull request replaces the usage of the deprecated pkg_resources with packaging. This makes `packaging` a mandatory dependency.

Fixes #64.

### CODE REVIEW

**Comment by real-yfprojects** [comment]
> Maybe we can vendor the functionality instead of introducing a hard dependency on the packaging package.

@johannesjh What's the benefit of that? Why maintain an half-baked implementation alongside integrating an optional dependency?

In this case, we would need to vendor multiple files of the `packaging` module for that to work.

**Comment by real-yfprojects** [comment]
I don't know what's the problem with `poetry.lock`. The local pre-commit hook passes.

**Comment by johannesjh** [comment]
I agree with what is proposed in this pull request, i.e., to make `packaging` a mandatory dependency, and to remove the vendored code.

Why did I vendor parts of packaging in the first place? My motivation is that I wanted to allow installation as a single script file, without any external dependencies. But I do agree that it takes quite a bit of work to maintain the vendored code. Is it worth the effort? Not sure, maybe not. 

Next steps for this pull request: can you update the documentation please, especially the section about the installation of req2flatpak, to clarify that req2flatpak needs the `packaging` package as a mandatory dependency. thanks!

**Comment by cbm755** [comment]
ping?  this looks good to me too.   Shall I tackle the docs bit in a new MR?

**Comment by johannesjh** [comment]
Thank you for this pull request. Thank you for all the good work! - Feel free to merge. (Tackling docs in a subsequent PR ist fine for me!)

**Pull request closed without merging**
