### PR TITLE
Updates dependencies

### PR DESCRIPTION
**Pull request by johannesjh**
this pull request aims at keeping dependencies up to date.

* [x] update github actions (manually)
* [x] update poetry dependencies by running `poetry update`
* [x] update pre-commit dependencies by running `pre-commit autoupdate --freeze`
* [x] update flatpak manifests (manually, and fix flatpak build errors along the way, add makefile to demonstrate usage)

### CODE REVIEW

**Review by real-yfprojects — CHANGES_REQUESTED** [review]
Ci fails

**Comment by johannesjh** [comment]
thank you, CI is working again. (poetry.lock was out of sync, that was why it failed)

**Comment by johannesjh** [comment]
Done with all the updates. Thank you for the helpful instructions in `development.rst`, it really helps to have these instructions at hand.

**Review by real-yfprojects — APPROVED** [review]

**Comment by johannesjh** [comment]
thank you for reviewing!

**Pull request merged**
